django1/django1/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

django1/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.xDetailView.as_view(), name='detail_vs_view'),
    # path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

django1/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    QUESTION = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

django1/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question  # looks locally in same folder, looks at models.py then import the Question Class

# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")

# ex: /polls/5/
def detail(request, question_id):
    # return HttpResponse("You're looking at question {}".format(question_id))

    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")
    # return render(request, 'polls/detail.html', {'question': question})

    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question_html': question})


# ex: /polls/5/results/
# def results(request, question_id):
#     # a custom return, no need to create a results page, dynamically post basic result
#     # response = "You're looking at the RESULTS of question {}.".format(question_id)
#     # return HttpResponse(response)
#
#
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question_html': question})

# ex: /polls/5/vote/
def vote(request, question_id):
    question_obj = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question_obj.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question_obj,
            'error_message': "You didn't select a CHOICE..CHOICE..CHOICE..CHOICE...",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question_obj.id,)))



# def index(request):
#     latest_question_list_query = Question.objects.order_by('-pub_date')[:5]
#     # template = loader.get_template('polls/index.html')  # not needed if use shortcut
#     context = {
#         'latest_question_list_to_html': latest_question_list_query,
#     }
#     # return HttpResponse(template.render(context, request)) # not needed if use shortcut
#     return render(request, 'polls/index.html', context)

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list_to_html'

    def get_queryset(self):
        """Return the last five published questions.(not including those set to be published in the future)."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class xDetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

django1/polls/templates/polls/detail.html
detail page

<h1>{{ question.question_text }}</h1>
<h2>ID: {{ question.id }}</h2>
<h2>PK: {{ question.pk }}</h2>
<h2>pub date: {{ question.pub_date }}</h2>



{% if error_message %} <h1><p style="color: red"><strong>{{ error_message }} error message if shows</strong></p></h1>{% endif %}


<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <div>
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        forloop.counter => {{ forloop.counter }}  id is : {{ choice.id }} --> current vote Count: {{choice.votes}}
        <label for="choice{{ forloop.counter }}">--- Label: {{ choice.choice_text }}</label>
    </div>
{% endfor %}
<input type="submit" value="Vote">
</form>

django1/polls/templates/polls/index.html
index page

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list_to_html %}
    <ul>
    {% for question in latest_question_list_to_html %}
        <li><a href="{% url 'polls:detail_vs_view' question.id %}">{{ question.question_text }}</a></li>
        {{question}}  {{ question.id }}
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

django1/polls/templates/polls/results.html
results page


<h1>{{ question.question_text}}</h1>

question# {{question.id}}

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail_vs_view' question.id %}">Vote again?</a>
<br>
<a href="{% url 'polls:index' %}">back to main</a>